### PR TITLE
Bump go.mod version to v2

### PR DESCRIPTION
**Pull request by pbusko**
## Summary

To reflect the actual major version and follow the official recommendation regarding `go.mod` versioning

## Use Cases

https://go.dev/doc/modules/version-numbers

> A major version update to a number higher than v1 will also have a new module path. That’s because the module path will have the major version number appended, as in the following example:
> 
> > module example.com/mymodule/v2 v2.0.0
>
> A major version update makes this a new module with a separate history from the module’s previous version. If you’re developing modules to publish for others, see “Publishing breaking API changes” in [Module release and versioning workflow](https://go.dev/doc/modules/release-workflow).

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by pacostas** [comment]
Hello @pbusko :wave: ! Thank you for your contribution :) Can you describe how consuming the versioned node-start from the node-start module will benefit the node-start module? I'm asking for a little bit of context as this change makes sense for consuming external modules, but I can not find a scenario where the same module would benefit from not consuming the latest version of itself. Also, it seems that this change is adding an extra step during development, as for consuming the latest version of the node-start you will have to make a publish first.

**Comment by pbusko** [comment]
https://github.com/paketo-buildpacks/node-engine/pull/966#issuecomment-2220177727

**Review by pacostas — APPROVED** [review]
LGTM

**Review by c0d1ngm0nk3y — APPROVED** [review]

**Comment by c0d1ngm0nk3y** [comment]
see discussions on https://github.com/paketo-buildpacks/node-engine/pull/966

**Comment by pacostas** [comment]
Related issue https://github.com/paketo-buildpacks/nodejs/issues/913

**Comment by mhdawson** [comment]
Based on discussion in https://github.com/paketo-buildpacks/nodejs/issues/913 we'll land these add hock for now. @pbusko can you rebase and then I'll land.

**Comment by pbusko** [comment]
Thank you @mhdawson, the PR has been rebased

**Review by pacostas — APPROVED** [review]
Based on this https://github.com/paketo-buildpacks/nodejs/issues/913#issuecomment-2275850807 , LGTM

**Comment by mhdawson** [comment]
@pbusko unfortunately seems to need another rebase. Will enable auto-merge so it should land as soon as the tests pass. I had started them yesterday but seems there was some change between then and now.

**Comment by pacostas** [comment]
@pbusko can you rebase again?

**Comment by pacostas** [comment]
@pbusko can you rebase once more? I thought the auto merge was enabled and in the mid-time another PR automatically landed. sorry :)

**Review by pacostas — APPROVED** [review]

**Pull request merged**
